### ISSUE TITLE
Cannot find module 'html-webpack-plugin'

### ISSUE THREAD

**Issue by bigandy** [shprink/wp-api-angularjs#3]
I ran 'npm install' then 'npm run watch' as specified in the readme. Got this error:

> wp-api-angularjs@1.0.0 watch /Users/andrew/Sites/wp-api-angularjs
> webpack --watch --progress --colors --config webpack.config.dist.js -d

module.js:338
    throw err;
          ^
Error: Cannot find module 'html-webpack-plugin'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/andrew/Sites/wp-api-angularjs/webpack.config.dist.js:4:25)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

**Comment by shprink** [comment]
Thanks for you PR. Is everything ok?
